### ISSUE TITLE
Unable to connect to MySQL over SSH

### ISSUE THREAD

**Issue by gabiudrescu** [d4software/QueryTree#16]
Operating system:
Ubuntu 17.10

Docker version:
```
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:10:09 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:08:36 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

# Steps to reproduce:
 - ran command `docker run -p 8080:80 --name querytree -d d4software/querytree:latest`
 - observe the container is running properly:
```
docker container ls
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                      NAMES
0403aa010a58        d4software/querytree:latest   "/bin/sh -c 'dotnet …"   42 seconds ago      Up 41 seconds       0.0.0.0:8080->80/tcp       querytree
```
 - go to web http://localhost:8080/
 - create account and login
 - create a connection to the MySQL server as shown below (successfully tested):
![localhost_8080_home_edit_1 1](https://user-images.githubusercontent.com/5156054/40302638-681b897c-5cf8-11e8-9bc6-0ea47a0a5684.png)
 - create a report

# What happens:
No tables are fetched from this connection, although tables exist and credentials are right (copy pasted them from our staging environment application configure file)
See below:
![localhost_8080_simple_create_connectionid 1](https://user-images.githubusercontent.com/5156054/40302719-bbeeb8f8-5cf8-11e8-88bf-d4494180e467.png)

Any ideas how can I see some verbose logs on what goes wrong?

Am I doing something wrong?

**Comment by gabiudrescu** [comment]
PS: I have edited the screenshots to mask some sensible information; I am connecting to the MySQL server over a SSH tunnel.

**Comment by gabiudrescu** [comment]
I rebuild the container to make sure I am using latest dev-master and ran it without the -d option and I have the following logs:
```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: Fatal error encountered during command execution.
MySql.Data.MySqlClient.MySqlException (0x80004005): Fatal error encountered during command execution. ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Fatal error encountered attempting to read the resultset. ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Reading from the stream has failed. ---> System.IO.IOException: Unable to read data from the transport connection: Connection timed out. ---> System.Net.Sockets.SocketException: Connection timed out
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at MySql.Data.MySqlClient.TimedStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at MySql.Data.MySqlClient.MySqlStream.ReadFully(Stream stream, Byte[] buffer, Int32 offset, Int32 count)
   at MySql.Data.MySqlClient.MySqlStream.LoadPacket()
   at MySql.Data.MySqlClient.MySqlStream.LoadPacket()
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at QueryTree.Managers.DbManager.GetDbModel(DatabaseType type, DbConnection conn, Int32 connectionId, String databaseName) in /build/Web/Managers/DbManager.cs:line 227
   at QueryTree.Managers.DbManager.<>c__DisplayClass5_0.<GetDbModel>b__0(DbConnection dbConn) in /build/Web/Managers/DbManager.cs:line 134
   at QueryTree.Managers.DbManager.<>c__DisplayClass12_0.<TryUseDbConnection>b__0(SSHProxy proxy) in /build/Web/Managers/DbManager.cs:line 557
   at QueryTree.Managers.SSHProxyManager.UseProxy(SSHProxy proxy, Action`1 action) in /build/Web/Managers/SSHProxyManager.cs:line 37
   at QueryTree.Managers.SSHProxyManager.TryUseProxy(String server, Int32 port, String sshServer, Int32 sshPort, SshProxyCredentials credentials, Action`1 action, String& error) in /build/Web/Managers/SSHProxyManager.cs:line 93
   at QueryTree.Managers.DbManager.TryUseDbConnection(DatabaseType type, String server, Int32 port, Boolean useSsh, String sshServer, Nullable`1 sshPort, SshProxyCredentials credentials, String username, String password, String databaseName, Action`1 action, String& error) in /build/Web/Managers/DbManager.cs:line 578
   at QueryTree.Managers.DbManager.TryUseDbConnection(DatabaseConnection connection, Action`1 action, String& error) in /build/Web/Managers/DbManager.cs:line 540
   at QueryTree.Managers.DbManager.GetDbModel(DatabaseConnection connection) in /build/Web/Managers/DbManager.cs:line 136
   at QueryTree.Controllers.ApiController.GetTables(Int32 databaseId) in /build/Web/Controllers/ApiController.cs:line 164
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
```

maybe it helps.

**Comment by PandelisZ** [comment]
Docker creates its own internal network when running within it. Localhost would be used as a lopback to itself not your pc's network.

Is MYSQL exposed on your host computer at 3306? If so using `localhost` in the setting wont work from within docker.

If on windows you could try `docker.for.win.localhost` which should loop back to your host. On mac its `docker.for.mac.localhost`

Related forum post: https://forums.docker.com/t/accessing-host-machine-from-within-docker-container/14248

That's what I can tell from your current configuration for now. Please let me know if that's the case.
