### ISSUE TITLE
Invitation not working

### ISSUE THREAD

**Issue by sidneydemoraes** [d4software/QueryTree#30]
Hello.
I already setup SMTP to the docker image but I can't say if it's working.
The main issue here is: whenever I try to invite someone to my team, the screen goes full blank without any error notice (nor on screen, nor on js console).

**Comment by ayr-ton** [comment]
@sidneydemoraes There's any log on the Docker container or from the dotnet daemon that is running?

**Comment by sidneydemoraes** [comment]
@ayr-ton Apparently not.

**Comment by ayr-ton** [comment]
@sidneydemoraes https://www.youtube.com/watch?v=-RcPZdihrp4

**Comment by sidneydemoraes** [comment]
Consegui acessar os logs com `docker logs -f`. Segue:

		fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
		  An unhandled exception has occurred: Could not find a part of the path '/app/EmailTemplates/InviteNewOrganisationUser.txt'.
		System.IO.DirectoryNotFoundException: Could not find a part of the path '/app/EmailTemplates/InviteNewOrganisationUser.txt'.
	   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
	   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
	   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
	   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
	   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
	   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
	   at System.IO.File.ReadAllText(String path)
	   at QueryTree.Controllers.TeamController.SendOrganisationInviteEmail(String fromEmail, String inviteEmail, Boolean inviteeAlreadyRegistered) in /build/Web/Controllers/TeamController.cs:line 490
	   at QueryTree.Controllers.TeamController.Invite(PermissionViewModel viewModel) in /build/Web/Controllers/TeamController.cs:line 258
	   at lambda_method(Closure , Object , Object[] )
	   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
	   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
	   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
	   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
	   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
	   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.<Invoke>d__3.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()

**Comment by sidneydemoraes** [comment]
@dand4 @ayr-ton Apparently it is a problem with the Docker image.
I created a new image based on yours and added the EmailTemplates folder from your git repo to `/app` and now invitation is working properly.

**Comment by dand4** [comment]
@sidneydemoraes @ayr-ton Thanks for your help in figuring this out. I've updated the Docker image to fix this.

**Comment by d0v1k** [comment]
still not working with latest docker image
how can i fix?

**Comment by d4nt** [comment]
@d0v1k have you set the smtp email settings? Check [docs/mail.md](docs/mail.md), you can set config settings using the -e option when running the docker image, see: [docs/docker.md#override-configuration-defaults](docs/docker.md#override-configuration-defaults)
